---
title: "Care sites application #2: PGS penetrance"
author: "Allie Lake"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    toc: true
    theme: united
    toc_depth: 4
---

# setup and load data
```{r setup, include = FALSE, message = FALSE, warning = FALSE, tidy = TRUE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, tidy = TRUE, fig.width=6, fig.height=4)
pacman::p_load(data.table, dplyr, foreach, PheWAS, ggplot2, plotly, ggpubr, scales, RColorBrewer, ggrepel, kableExtra, broom)
setwd("/data/davis_lab/allie/care_sites/scripts")
```

```{r}
#### OR formatting function ####
or_format_func <- function(OR, ci_lower, ci_upper) {
  return(
    paste0(sprintf(
      "%s (%s-%s)",
      formatC(OR, format = "f", digits = 2),
      formatC(ci_lower, format = "f", digits = 2),
      formatC(ci_upper, format = "f", digits = 2)
    ))
  )
}

#### Function to process logistic regression output ####
process_logit <- function(mdl) {
  output <- tidy(mdl)
  output$OR <- exp(output$estimate)
  output$ci.lower <- exp(output$estimate-1.96*output$std.error)
  output$ci.upper <- exp(output$estimate+1.96*output$std.error)
  output
}


#### Rounding function for p-values ####
rounding_func <- function(xx) {
  if (is.na(xx)) {
    return(NA)
  } else if (xx < 1e-3) {
    # y <- formatC(xx, format = "e", digits = 2)
    y <- "<0.001"
  } else if (round(xx,2) <0.01) { # <0.01 and ≥0.001 -> 3 digits 
    y <- formatC(xx, format = "f", digits = 3)
  } else { # ≥0.01 -> 2 digits
    y <- formatC(xx, format = "f", digits = 2)
  }
  return(as.character(y))
}

```

## Load data compiled in compile_data.R
```{r}
## load care site map
map <- fread("/data/davis_lab/allie/care_sites/output/CareSiteMap_Multispecialty_Long_UPDATED_0924.csv")

## load covariates, PGS, and phecodes
dat <- readRDS("/data/davis_lab/allie/care_sites/data/mdd_application/mega_eur_afr_covariates_pgs_phecodes_092424.Rds")

## remove phecode columns except for mdd
setnames(dat, "296.22", "mdd")
phe_cols<- names(dat)[grepl("^[[:digit:]]", names(dat))]
dat <- dat[,-phe_cols,with=F]

## recode pheno columns
dat$mdd <- as.numeric(dat$mdd)
dat[is.na(mdd), mdd := -9]
```

```{r}
## load visit info
visit <- fread("/data/davis_lab/allie/care_sites/data/mdd_application/mega_grids_visits_cleaned_dates_non_null_sites.csv")
```

# MDD
## depression definitions
* Definition 1: standard MDD phecode (296.22)
* Definition 2: 
  * case = has MDD phecode (296.22) + ≥1 psych site visit (i.e., MDD diagnosed by a psychiatrist)
  * control = no MDD phecode (296.22)
  * excluded = has MDD phecode (296.22) but no psych site visit or is N/A for MDD phecode
```{r}
psych_sites <- unique(map[SpecialtyLong == "Psychiatry", care_site_id])
psych_grids <- unique(visit[care_site_id %in% psych_sites, GRID])
dat[, psych_cohort := as.numeric(GRID %in% psych_grids)]

dat[, mdd_psych_site := ifelse(mdd==1 & psych_cohort==1, 1,
                                ifelse(mdd==0,0,-9))]
```

```{r}
dat %>%
  group_by(mdd) %>%
  summarise(n = n()) %>%
  mutate(perc = n/nrow(dat)) %>% 
  kable(digits = 2) %>% 
  kable_styling()

dat %>%
  group_by(mdd_psych_site) %>%
  summarise(n = n()) %>%
  mutate(perc = n/nrow(dat)) %>% 
  kable(digits = 2) %>% 
  kable_styling()

dat$mdd_lab <- factor(dat$mdd, levels = c(0,1,-9), labels = c("No MDD", "MDD", "Excluded from MDD phenotype"))
dat$mdd_psych_site_lab <- factor(dat$mdd_psych_site, levels = c(0,1,-9), labels = c("No MDD+", "MDD+","Excluded from MDD+ phenotype"))

table(dat$mdd_lab, dat$mdd_psych_site_lab) %>% 
  kable() %>% 
  kable_styling()
```

## analysis
```{r}
mdl_mdd <- glm(mdd ~ pgs.dep.scale + sex + median_age + PC1+PC2+PC3+PC4+PC5+PC6+PC7+PC8+PC9+PC10, 
           data = dat[genetic_ancestry == "EUR" & mdd!=-9], family = "binomial")

mdl_mdd_psych_site <- glm(mdd_psych_site ~ pgs.dep.scale + sex + median_age + PC1+PC2+PC3+PC4+PC5+PC6+PC7+PC8+PC9+PC10, 
           data = dat[genetic_ancestry == "EUR" & mdd_psych_site!=-9], family = "binomial")

res_mdd <- rbind(process_logit(mdl_mdd) %>% mutate(pheno = "MDD"),
             process_logit(mdl_mdd_psych_site) %>% mutate(pheno = "MDD+psych_site")) %>% 
       data.table()


res_mdd[, OR_format := apply(.SD, 1, function(x) or_format_func(x[1], x[2], x[3])), .SDcols = c("OR", "ci.lower", "ci.upper")]
res_mdd$p.value.fmt <- sapply(res_mdd$p.value, rounding_func)

res_mdd %>% 
  filter(term == "pgs.dep.scale") %>% 
  select(pheno, OR_format, p.value.fmt) %>%
  kable() %>%
  kable_styling()
```